name: pml_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_sign_in: 5.2.1
  firebase_auth: 3.1.4
  lottie: 1.2.1
  introduction_screen: 2.1.0
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.0.7
  get_storage: 2.0.3
  cloud_firestore: 3.1.0
  firebase_core: 1.10.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
  uses-material-design: true

